[LilyGo_THigrow]
extends = esp32_base ; ESP32-D0WDQ6-V3
board = esp32dev ; LILYGO T-Higrow with SX1276 LoRa Shield
build_flags =
  ${esp32_base.build_flags}
  -I variants/lilygo_thigrow
  -D LILYGO_THIGROW
  -D RADIO_CLASS=CustomSX1276
  -D WRAPPER_CLASS=CustomSX1276Wrapper
  -D P_LORA_DIO_0=14
  -D P_LORA_DIO_1=13
  -D P_LORA_DIO_2=15
  -D P_LORA_NSS=18
  -D P_LORA_RESET=23
  -D P_LORA_BUSY=18
  -D P_LORA_SCLK=5
  -D P_LORA_MISO=19
  -D P_LORA_MOSI=27
  -D PIN_BTN_BOOT=0
  -D PIN_BTN_USER=35
  -D PIN_BOARD_SDA=25
  -D PIN_BOARD_SCL=26
  -D PIN_BAT_CTL=4
  -D PIN_VBAT_READ=33 ; YDL 3.7V 200mAh 402030 Lipo Battery Rechargeable
  -D LORA_TX_POWER=10
  -D MAX_LORA_TX_POWER=20
  -D SALT_PIN=34 ; fertility
  -D SOIL_PIN=32 ; moisture
  -D TELEM_BH1750_ADDRESS=0x23
  -D TELEM_DHT_PIN=16
  -D TELEM_BME280_ADDRESS=0x77
build_src_filter = ${esp32_base.build_src_filter}
  +<../variants/lilygo_thigrow>
lib_deps =
  ${esp32_base.lib_deps}
  adafruit/Adafruit BME280 Library @ ^2.3.0
  adafruit/DHT sensor library @ ^1.4.7
  wollewald/BH1750_WE @ ^1.1.10

[env:LilyGo_THigrow_sensor]
extends = LilyGo_THigrow
build_flags =
  ${LilyGo_THigrow.build_flags}
  -D DISPLAY_CLASS=NullDisplayDriver
;  -D USE_INTERUPT_BUTTON=1
  -D ADVERT_NAME='"THigrow Sensor"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter =
  ${LilyGo_THigrow.build_src_filter}
  +<helpers/ui/NullDisplayDriver.cpp>
  +<../examples/simple_sensor>
lib_deps =
  ${LilyGo_THigrow.lib_deps}
  ${esp32_ota.lib_deps}
